### ISSUE TITLE
`method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x00007fc2af60afd0> (NoMethodError)

### ISSUE THREAD

**Issue by kevin-jj** [ankane/searchjoy#39]
It does not work if a rails project is created with --skip-sprockets.  @ankane 

```ruby
1: from /Users/xxx/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/searchjoy-0.4.1/lib/searchjoy/engine.rb:7:in `block in <class:Engine>'

/Users/xxxx/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x00007fc2af60afd0> (NoMethodError)

```

**Comment by ankane** [comment]
Hey @kevin-jj, Searchjoy uses Sprockets for assets, so it won't work with that option.

**Comment by kevin-jj** [comment]
It work well in Rails 5.2 but 6.0
